name: ci
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v7
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/coursier
          ~/.ivy2/cache
          ~/.sbt
          !~/.ivy2/.sbt.ivy.lock
          !~/.ivy2/cache/**/ivydata-*.properties
          !~/.sbt/**/*.lock
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - run: sbt validate
    - uses: codecov/codecov-action@v1
