name: release
on:
  push:
    branches: ['master']
    tags: ['*']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v7
    - uses: olafurpg/setup-gpg@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/coursier
          ~/.ivy2/cache
          ~/.sbt
          !~/.ivy2/.sbt.ivy.lock
          !~/.ivy2/cache/**/ivydata-*.properties
          !~/.sbt/**/*.lock
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - run: sbt ci-release docs/docusaurusPublishGhpages
      env:
        GITHUB_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
